# 简历来源分析

SQB01 : 测试
SQB02 : 开发
SQB03 : 运维
SQB04 : 数据
SQB05 : 数据
SQB06 : 数据
SQB07 : 数据
SQB08 : 测试
SQB09 : 测试
SQB10 : 测试
SQB11 : 开发
SQB12 : 开发
SQB13 : 开发
SQB14 : 开发
SQB15 : 测试
SQB16 : 运维
SQB17 : 产品
SQB18 : 产品
SQB19 : 产品
SQB20 : 产品
SQB21 : 产品
SQB22 : 产品
SQB23 : 产品
SQB24 : 其他
SQB25 : 其他
SQB26 : 其他
SQB27 : 测试
SQB28 : 其他
SQB29 : 开发
SQB30 : 运维
SQB31 : 测试
SQB32 : 测试
SQB33 : 测试
SQB34 : 测试
SQB35 : 测试
SQB36 : 测试
SQB37 : 测试
SQB38 : 测试
SQB39 : 测试
SQB40 : 测试
SQB41 : 测试
SQB42 : 测试
HQB01 : 测试
HQB02 : 测试
HQB03 : 测试
HQB04 : 测试
HQB05 : 测试
DQB01 : 测试
DQB02 : 测试
DQB03 : 测试
DQB04 : 测试
DQB05 : 测试
SDB01 : 测试
SDB02 : 测试
SDB03 : 运维
SDB04 : 运维
SDB05 : 数据
SDB06 : 数据
SDB07 : 数据
SDB08 : 测试
SDB09 : 测试
SDB10 : 测试
SDB11 : 开发
SDB12 : 开发
SDB13 : 开发
SDB14 : 开发
SDB15 : 测试
SDB16 : 运维
SDB17 : 产品
SDB18 : 产品
SDB19 : 产品
SDB20 : 产品
SDB21 : 产品
SDB22 : 产品
SDB23 : 产品
SDB24 : 其他
SDB25 : 其他
SDB26 : 其他
SDB27 : 测试
SDB28 : 其他
SDB29 : 开发
SDB30 : 运维
SDB31 : 测试
SDB32 : 测试
SDB33 : 运维
SDB34 : 数据
SDB35 : 产品
SDB36 : 开发
SDB37 : 产品
SDB38 : 运维
SDB39 : 产品
SDB40 : 数据
SDB41 : 测试
SDB42 : 开发
SDB43 : 开发
SDB44 : 开发
SDB45 : 测试
SDB46 : 测试
SDB47 : 测试
SDB48 : 测试
SDB49 : 测试
SDB50 : 测试
SDB51 : 测试
SDB52 : 测试
SDB53 : 测试
SDB54 : 测试
SDB55 : 测试
SDB56 : 测试
SDB57 : 测试
SDB58 : 测试
SDB59 : 测试
SDB60 : 测试
SDB61 : 开发
SDB62 : 开发
SDB63 : 开发
SDB64 : 开发
SDB65 : 测试
SDB66 : 开发
SDB67 : 测试
SDB68 : 测试
SDB69 : 测试
HDB01 : 测试
HDB02 : 测试
HDB03 : 测试
HDB04 : 测试
HDB05 : 测试
DDB01 : 测试
DDB02 : 测试
DDB03 : 测试
DDB04 : 测试
DDB05 : 测试
SCR01 : 测试
SCR02 : 测试
SCR03 : 运维
SCR04 : 运维
SCR05 : 数据
SCR06 : 数据
SCR07 : 数据
SCR08 : 测试
SCR09 : 测试
SCR10 : 测试
SCR11 : 开发
SCR12 : 开发
SCR13 : 开发
SCR14 : 开发
SCR15 : 测试
SCR16 : 运维
SCR17 : 产品
SCR18 : 产品
SCR19 : 产品
SCR20 : 产品
SCR21 : 产品
SCR22 : 产品
SCR23 : 产品
SCR24 : 其他
SCR25 : 其他
SCR26 : 其他
SCR27 : 测试
SCR28 : 其他
SCR29 : 开发
SCR30 : 运维
HCB01 : 测试
HCB02 : 测试
HCB03 : 测试
HCB04 : 测试
HCB05 : 测试
DCB01 : 测试
DCB02 : 测试
DCB03 : 测试
DCB04 : 测试
DCB05 : 测试
SCR31 : 开发
SCR32 : 测试
SCR33 : 开发
SCR34 : 数据
SCR35 : 测试
SCR36 : 产品
SCR37 : 测试
SCR38 : 开发
SCR39 : 开发
SCR40 : 测试
SCR41 : 测试
SCR42 : 测试
SCR43 : 产品
SCR44 : 开发
SCR45 : 开发
SCR46 : 测试
SCR47 : 开发
SCR48 : 测试
SCR49 : 运维
SCR50 : 开发
SCR51 : 测试
SCR52 : 运维
SCR53 : 数据
SCR54 : 产品
SCR55 : 产品
SCR56 : 运维
SCR57 : 产品
SCR58 : 开发
SCR59 : 测试
SCR60 : 测试
SCR61 : 测试
SCR62 : 测试
SCR63 : 测试
SCR64 : 测试
SCR65 : 测试
SCR66 : 测试
SCR67 : 测试
SCR68 : 测试
SCR69 : 测试
SCR70: 测试
SCR71: 测试
SCR72: 测试
SCR73: 开发
SQR01 : 测试
SQR02 : 运维
SQR03 : 运维
SQR04 : 测试
SQR05 : 数据
SQR06 : 测试
SQR07 : 数据
SQR08 : 测试
SQR09 : 测试
SQR10 : 运维
SQR11 : 测试
SQR12 : 运维
SQR13 : 运维
SQR14 : 产品
SQR15 : 开发
SQR16 : 产品
SQR17 : 运维
SQR18 : 测试
SQR19 : 产品
SQR20 : 运维
SQR21 : 测试
SQR22 : 测试
SQR23 : 开发
SQR24 : 开发
SQR25 : 测试
SQR26 : 产品
SQR27 : 开发
SQR28 : 测试
SQR29 : 开发
SQR30 : 开发
SQR31 : 测试
SQR32 : 测试
SQR33 : 测试
SQR34 : 测试
SQR35 : 测试
SQR36 : 测试
SQR37 : 测试
SQR38 : 测试
SQR39: 测试
SQR40: 测试
SQR41: 测试
SQR42: 测试
SQR43: 测试
SQR44: 测试
SQR45: 测试
SQR46: 测试
SQR46: 产品
SCZ01 : 数据
SCZ02 : 测试
SCZ03 : 测试
SCZ04 : 开发
SCZ05 : 开发
SCZ06 : 测试
SCZ07 : 开发
SCZ08 : 测试
SCZ09 : 测试
SCZ10 : 测试
SCZ11: 测试
SCZ12: 测试
SCZ13: 测试
SCZ50 : 测试
SCZ51 : 测试
SCZ52 : 测试
SCZ53 : 测试
SCZ54 : 测试
SCZ55: 测试
SCZ56: 测试
SCZ57: 测试
SCZ58: 测试
SCZ59: 测试
SCZ60: 测试
